language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t kellydouglass/front -f ./front/Dockerfile.dev ./front

script:
  - docker run -e CI=true kellydouglass/front npm test -- --coverage