language: generic
sudo: required

branches:
  only:
    - main

services:
  - docker

before_install:
  - docker build -t kellydouglass/front -f ./front/Dockerfile.dev ./front

script:
  - docker run -e CI=true kellydouglass/front npm test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_TEMP_KEY"
  app: kelly-docker-practice-2
  on:
    branch: main
    # repo: nostradouglass/kellyDockerPractice2