version: "3"

services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        volumes:
            - /app/node_modules
            - ./api:/app
    front:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./front
        volumes:
            - /app/node_modules
            - ./front:/app
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'