version: "3"

services:
    api:
        image: kellydouglass/dockerpractice2_api
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        volumes:
            - /app/node_modules
            - ./api:/app
    front:
        stdin_open: true
        image: kellydouglass/dockerpractice2_front
        build:
            dockerfile: Dockerfile.dev
            context: ./front
        volumes:
            - /app/node_modules
            - ./front:/app
    nginx:
        depends_on: 
            - front
            - api
        restart: always
        image: kellydouglass/dockerpractice2_nginx
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'